(add-hook 'gdb-mode-hook 'gdb-refresh-all)

(global-set-key [double-down-mouse-1] 'gud-print)
(global-set-key [C-down-mouse-3] 'gud-print)

(global-set-key (kbd "C-c b") 'gud-break)
(global-set-key (kbd "C-c t") 'gud-tbreak)
(global-set-key (kbd "C-c d") 'gud-remove)
(global-set-key (kbd "C-c p") 'gud-print)
(global-set-key (kbd "C-c P") 'gud-pstar)
(global-set-key (kbd "C-c w") 'gdb-watch)
(global-set-key (kbd "C-c c") 'gud-next)
(global-set-key (kbd "C-c s") 'gud-step)
(global-set-key (kbd "C-c u") 'gud-cont)

(global-set-key [f1] 'gud-next)
(global-set-key [f2] 'gud-step)
(global-set-key [f3] 'gud-print)
(global-set-key [f5] 'gdb-refresh-all)
(global-set-key [f7] 'gud-break)
(global-set-key [f8] 'gud-cont)
(global-set-key [f9] 'gud-run)
(defun gdb-watch ()
  (interactive)
  (gud-watch)
  (speedbar-get-focus))

;; (setq gdb-gud-control-all-threads nil)
;; (setq gdb-switch-when-another-stopped nil)
;; (setq gdb-show-changed-values t)
(setq gdb-non-stop-setting nil)

(require 'gud)
(gud-def gdb-refresh "update" nil "")
(gud-def gdb-baz-next "next" nil "")
(gud-def gdb-baz-step "step" nil "")
(gud-def gdb-baz-cont "continue" nil "")


(global-set-key (kbd "C-c r") 'gdb-refresh-all)
(global-set-key (kbd "C-c n") 'gdb-refresh)


(defun gdb-refresh-all ()
  (interactive)
  (delete-other-windows)
  (gdb-frame-gdb-buffer)
  (split-window-right)
  (other-window 1)
  ;; (split-window-below)
  (split-window-below)
  (other-window -1)
  ;; (gdb-display-stack-buffer)
  (gdb-display-breakpoints-buffer)
  (gdb-display-io-buffer)
  (gud-refresh))

;;(defun gdb-next (&optional args)
;;  (interactive)
;;  (gdb-baz-next args)
;;  (gdb-refresh args))
